version: '3.9'

services:
  scrobblex:
    container_name: scrobblex
    image: scrobblex
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - $PORT:$PORT
    environment:
      - TRAKT_ID=$TRAKT_ID
      - TRAKT_SECRET=$TRAKT_SECRET
    volumes:
      - ./scrobblex:/data
