services:
  scrobblex:
    image: ghcr.io/ryck/scrobblex:latest
    container_name: scrobblex
    restart: always
    ports:
      - $PORT:$PORT
    environment:
      - TRAKT_ID=$TRAKT_ID
      - TRAKT_SECRET=$TRAKT_SECRET
      - LOG_LEVEL=$LOG_LEVEL
    volumes:
      - ./scrobblex:/app/data
